### PR TITLE
Mirror magic

### PR DESCRIPTION
**Pull request by jechols**
ALL the data

### CODE REVIEW

**Comment by jduss4** [comment]
I think this looks good except for the script you wrote.  Could you change a few lines?  ....to python?  :)

**Comment by jduss4** [comment]
So obviously this works, thanks for grabbing all the marc data!  However, I don't know enough about Go to do anything more than a weak code review.  My only thoughts:
- if the marc directories were all in a "marc" directory, we could see the main readme right away instead of having to scroll very far down
- could you add instructions to the readme about how to run the script?

Thanks!  :)

**Comment by jechols** [comment]
Yes, a marc directory makes sense.  Good idea.

The Go bit was really not even going to be in the repo because it was my dumb little one-off, but then I was like, meh, it's better than providing nothing.  I won't rewrite it, though :P

**Comment by jechols** [comment]
@jduss4: Done!

**Comment by jduss4** [comment]
I appreciate the script in here, because then potentially nobody else will have to make their own later.  So, woo.

**Pull request merged**
